blog/urls.py
from django.urls import path
from . import views


app_name = "blog"

urlpatterns = [
    path('', views.home, name="home"),
    path('post/<slug:slug>/', views.detail, name="detail"),
    path('categories/', views.categories, name="categories"),
    path('categories/<slug:slug>/', views.category, name="category"),
    path('tags/', views.tags, name="tags"),
    path('tags/<slug:slug>/', views.tag, name="tag"),
]

contact/urls.py
from django.urls import path
from . import views


app_name = 'contact'
urlpatterns = [
    path('', views.get_contact, name="contact"),
    path('success/', views.success_contact, name="success")
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('contact/', include('contact.urls')),
    path('newsletter/', include('newsletter.urls')),
    path('plans/', include('services.urls')),
    path('portfolio/', include('portfolio.urls')),
    path('', include('home.urls')),
]

home/urls.py
from django.urls import path
from . import views


app_name = 'home'
urlpatterns = [
    path('', views.index, name="index"),
]

services/urls.py
from django.urls import path
from . import views


app_name = "services"
urlpatterns = [
    path("", views.home, name="home"),
    path("website/<slug:slug>/", views.website, name="website"),
]

home/models.py
from django.db import models

# Create your models here.

services/models.py
from django.db import models
from django.urls import reverse
from core.models import TimeStampedModel, PublishedManager
from offer.models import Offer


class website(TimeStampedModel):
    title = models.CharField(max_length=200, verbose_name='Title')
    slug = models.SlugField(max_length=200, verbose_name='Slug')
    template = models.CharField(max_length=200, verbose_name="Template")
    domain = models.CharField(max_length=200, verbose_name="Domain")
    host = models.CharField(max_length=200, verbose_name="Host")
    support = models.CharField(max_length=200, verbose_name="Support", blank=True)
    op_1 = models.CharField(max_length=200, verbose_name="Option 1", blank=True)
    op_2 = models.CharField(max_length=200, verbose_name="Option 2", blank=True)
    op_3 = models.CharField(max_length=200, verbose_name="Option 3", blank=True)
    op_4 = models.CharField(max_length=200, verbose_name="Option 4", blank=True)
    op_5 = models.CharField(max_length=200, verbose_name="Option 5", blank=True)
    op_6 = models.CharField(max_length=200, verbose_name="Option 6", blank=True)
    op_7 = models.CharField(max_length=200, verbose_name="Option 7", blank=True)
    op_8 = models.CharField(max_length=200, verbose_name="Option 8", blank=True)
    op_9 = models.CharField(max_length=200, verbose_name="Option 9", blank=True)
    desc = models.TextField(verbose_name="Description", blank=True)
    price = models.CharField(max_length=50, verbose_name="Price")
    offer = models.ForeignKey(Offer, on_delete=models.CASCADE, blank=True, null=True, verbose_name="Offer")
    sort = models.IntegerField(blank=True, null=True, verbose_name="Sorting")
    publish = models.BooleanField(verbose_name="Publish", default=True)

    objects = models.Manager()  # The default manager
    published = PublishedManager()  # The published posts manager

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("services:website", kwargs={"slug": self.slug})
    

home/views.py
from django.shortcuts import render
from services import models as services_models


def index(request):
    plans = services_models.website.published.all()
    context = {
        'plans': plans,
    }
    return render(request, 'home/index.html', context)

services/views.py
from django.shortcuts import render, get_object_or_404
from . import models
from offer.views import get_offer


def home(request):
    web_plans = models.website.published.order_by('sort')
    context = {'web_plans': web_plans,}
    return render(request, 'services/home.html', context)

def website(request, slug):
    plan = get_object_or_404(models.website, slug=slug)

    # Get offer from get_offer() function
    offer_price = get_offer(plan)

    context = {
        'plan': plan,
        'offer_price': offer_price,
    }
    return render(request, 'services/web_plan.html', context)

home/templates/home/base.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>

        {% include 'home/head.html' %}
        {% block styles %}{% endblock styles%}

        <title>
            {% block title %}Kiwi Web کیوی وب{% endblock title%}
        </title>

    </head>

    <body>

        {% block content %} {% endblock content %}




        <!--    JS scripts    -->
        <script src="{% static 'home/js/jquery-2.2.4.min.js' %}"></script>
        <script src="{% static 'home/js/materialize.min.js' %}"></script>
        <script src="{% static 'home/js/init.js' %}"></script>
        <script src="{% static 'home/owl/owl.carousel.min.js' %}"></script>
        <script src="{% static 'home/owl/zepto.min.js' %}"></script>
        {% block scripts %}{% endblock scripts %}
        <!--    End of JS scripts    -->
    </body>
</html> 

home/templates/home/head.html
{% load static %}

<meta charset="UTF-8">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="description" content="کیوی وب - طراحی سایت و اپلیکیشن">
<meta name="keywords" content="KiwiWeb, کیوی وب,Web Design, طراحی سایت, طراحی اپلیکیشن">
<meta name="author" content="Aref Fallah - عارف فلاح">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="theme-color" content="#fff"/>

<!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
<![endif]-->

<link href="{% static 'home/css/style.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
<link href="{% static 'home/css/materialize.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
<link href="{% static 'home/css/materialize.rtl.min.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

home/templates/home/header.html
{% load static %}

<section id="header">

    {% include 'home/navbar.html' %}

    <img src="{% static 'home/img/laptop_model2.svg' %}">

    <div class="title">
        <h1 class="center">کیوی وب</h1>
        <h3 class="center">طراحی سایت و اپلیکیشن</h3>
    </div>

</section>

home/templates/home/index.html
{% extends 'home/base.html' %}

{% block title %}
sadsad
{% endblock %}

{% block content %}

    {% include 'home/header.html' %}

    <div class="clearfix"></div>

    {% include 'home/services.html'%}

    <div class="clearfix"></div>

{% endblock content %}

home/templates/home/navbar.html
{% load static %}

<div class="">
  <nav>
      <div class="nav-wrapper">
        <a href="{% url 'home:index' %}" class="left brand-logo cyan-text text-darken-2">
        <img src="{% static 'home/img/logo.svg' %}"></a>
        <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="fa fa-bars fa-2x"></i></a>
        <ul class="right hide-on-med-and-down">
          <li><a href="{% url 'home:index' %}">خانه</a></li>
          <li><a href="{% url 'services:home' %}">خدمات</a></li>
          <li><a href="{% url 'blog:home' %}">وبلاگ</a></li>
          <li><a href="{% url 'contact:contact' %}" class="highlight">تماس با ما</a></li>
        </ul>
      </div>
  </nav>
</div>

<ul class="sidenav" id="mobile-demo">
    <li><a href="{% url 'home:index' %}">خانه</a></li>
    <li><a href="{% url 'services:home' %}">خدمات</a></li>
    <li><a href="{% url 'blog:home' %}">وبلاگ</a></li>
    <li><a href="{% url 'contact:contact' %}">تماس با ما</a></li>
</ul>

home/templates/home/services.html
{% load static %}

<section id="services">

    <div class="row">
        <div class="col s12 m12 l6 service_item">
            <div class="row">
                <div class="col s12 m4 l4">
                    <img src="{% static 'home/img/icon_monitor.svg'%}">
                </div>
                <div class="col s12 m8 l8">
                    <h3> طراحی سایت و اپلیکیشن </h3>
                    <p>
                    لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد.
                    </p>
                </div>
            </div>
        </div>

        <div class="col s12 m12 l6 service_item">
            <div class="row">
                <div class="col s12 m4 l4">
                    <img src="{% static 'home/img/icon_idea.svg'%}">
                </div>
                <div class="col s12 m8 l8">
                    <h3> استارت آپ </h3>
                    <p>
                    لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد.
                    </p>
                </div>
            </div>
        </div>

        <div class="clearfix"></div>

        <div class="col s12 m12 l6 service_item">
            <div class="row">
                <div class="col s12 m4 l4">
                    <img src="{% static 'home/img/icon_seo_g.svg'%}">
                </div>
                <div class="col s12 m8 l8">
                    <h3> سئو </h3>
                    <p>
                    لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد.
                    </p>
                </div>
            </div>
        </div>

        <div class="col s12 m12 l6 service_item">
            <div class="row">
                <div class="col s12 m4 l4">
                    <img src="{% static 'home/img/icon_target.svg'%}">
                </div>
                <div class="col s12 m8 l8">
                    <h3> مارکتینگ </h3>
                    <p>
                    لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد.
                    </p>
                </div>
            </div>
        </div>

        







    </div>

</section>