blog/urls.py
from django.urls import path
from . import views


app_name = "blog"

urlpatterns = [
    path('', views.home, name="home"),
    path('post/<slug:slug>/', views.detail, name="detail"),
    path('categories/', views.categories, name="categories"),
    path('categories/<slug:slug>/', views.category, name="category"),
    path('tags/', views.tags, name="tags"),
    path('tags/<slug:slug>/', views.tag, name="tag"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('contact/', include('contact.urls')),
    path('newsletter/', include('newsletter.urls')),
    path('plans/', include('services.urls')),
    path('portfolio/', include('portfolio.urls')),
    path('', include('home.urls')),
]

home/urls.py
from django.urls import path
from . import views


app_name = 'home'
urlpatterns = [
    path('', views.index, name="index"),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils import timezone
from core.models import TimeStampedModel, PublishedManager
from . import views


class Category(TimeStampedModel):
    title = models.CharField(max_length=250, verbose_name="Title", unique=True)
    slug = models.SlugField(max_length=250, verbose_name="Slug", unique=True)

    class Meta:
        ordering = ('slug', '-created', '-modified')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("blog:category", kwargs={"slug": self.slug})
    


class Tag(TimeStampedModel):
    title = models.CharField(max_length=250, verbose_name="Title", unique=True)
    slug = models.SlugField(max_length=250, verbose_name="Slug", unique=True)

    class Meta:
        ordering = ('slug', '-created', '-modified')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("blog:tag", kwargs={"slug": self.slug})


class Post(TimeStampedModel):
    title = models.CharField(max_length=250, verbose_name="Title")
    slug = models.SlugField(max_length=250, verbose_name="Slug", unique=True)
    content = models.TextField(verbose_name="Content")
    categories = models.ManyToManyField(Category, related_name="posts", blank=True, verbose_name="Categories")
    tags = models.ManyToManyField(Tag, related_name="posts", blank=True, verbose_name="Tags")
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="posts", verbose_name="Author")
    date = models.DateTimeField(default=timezone.now, verbose_name="Publish date")
    publish = models.BooleanField(verbose_name="Publish", default=False)

    objects = models.Manager()  # The default manager
    published = PublishedManager()  # The published posts manager

    class Meta:
        ordering: ('-date', 'title', 'author',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("blog:detail", kwargs={"slug": self.slug})
    


class Comment(TimeStampedModel):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments", verbose_name="Post")
    name = models.CharField(max_length=100, verbose_name="Name")
    email = models.EmailField(verbose_name="Email")
    content = models.TextField(verbose_name="Content")
    publish = models.BooleanField(verbose_name="Publish", default=True)
    
    objects = models.Manager()
    published = PublishedManager()

    class Meta:
        ordering: ('-created', 'name', 'email',)

    def __str__(self):
        return self.email

home/models.py
from django.db import models

# Create your models here.

blog/views.py
from django.shortcuts import render, get_object_or_404
from . import models


def home(request):
    posts = models.Post.published.order_by('-date')[:5]
    context = {'posts': posts,}
    return render(request, 'blog/home.html', context)


def detail(request, slug):
    post = get_object_or_404(models.Post, slug=slug)
    comments = post.comments.filter(publish=True).order_by('-created')
    context = {
        'post': post,
        'comments': comments,
    }
    return render(request, 'blog/post.html', context)


def categories(request):
    cats = models.Category.objects.all()
    context = {'cats': cats,}
    return render(request, 'blog/categories.html', context)


def category(request, slug):
    cat = get_object_or_404(models.Category, slug=slug)
    context = {'cat': cat,}
    return render(request, 'blog/category.html', context)


def tags(request):
    tags = models.Tag.objects.all()
    context = {'tags': tags,}
    return render(request, 'blog/tags.html', context)


def tag(request, slug):
    tag = get_object_or_404(models.Tag, slug=slug)
    context = {'tag': tag}
    return render(request, 'blog/tag.html', context)

home/views.py
from django.shortcuts import render
from services import models as services_models


def index(request):
    plans = services_models.website.published.all()
    context = {
        'plans': plans,
    }
    return render(request, 'home/index.html', context)

blog/templates/blog/categories.html
{% if cats %}
    {% for cat in cats %}

        <p>
            <a href="{{ cat.get_absolute_url }}">{{ cat.title }}
        </p>

    {% endfor %}
    <br>
    <a href="{% url 'blog:home' %}">Blog Index</a>

{% endif %}

blog/templates/blog/category.html
{% if cat %}

    <p>
        <h2>{{ cat.title }}</h2>

        {% for post in cat.posts.all %}
        <p>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </p>
        {% endfor %}
    </p>
    <br>
    <a href="{% url 'blog:categories' %}">Cats Index</a>

{% endif %}

blog/templates/blog/detail.html
{% if post %}

    <p>
        <h2>{{ post.title }}</h2>
        {% for cat in post.categories.all %}
            {{ cat.title }}, 
        {% endfor %}
        <br>
        {% for tag in post.tags.all %}
            {{ tag.title }}, 
        {% endfor %}
    </p>
    <br>
    <a href="{% url 'blog:home' %}">Blog Index</a>

    <hr>
    <p>


        {% for cmnt in comments %}
            {{ cmnt.name }} _ {{ cmnt.email }} _ <code>{{cmnt.created}}</code>
            <p>
                {{ cmnt.content }}
            </p>
        {% endfor %}


    </p>

{% endif %}

blog/templates/blog/home.html
{% if posts %}
    {% for post in posts %}

        <p>
            <h2><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
            {% for cat in post.categories.all %}
                <a href="{{ cat.get_absolute_url }}">{{ cat.title }}</a>,
            {% endfor %}
            <br>
            {% for tag in post.tags.all %}
                <a href="{{ tag.get_absolute_url }}">{{ tag.title }}</a>, 
            {% endfor %}
        </p>

    {% endfor %}

{% endif %}

<br>
<a href="{% url "blog:tags" %}">Tags</a>
<br>
<a href="{% url "blog:categories" %}">Cats</a>

blog/templates/blog/post.html
{% if post %}

    <p>
        <h2>{{ post.title }}</h2><h5>{{ post.author }} | {{ post.date }}</h5>
        {% for cat in post.categories.all %}
            <a href="{{ cat.get_absolute_url }}">{{ cat.title }}</a>,
        {% endfor %}
        <br>
        {% for tag in post.tags.all %}
            <a href="{{ tag.get_absolute_url }}">{{ tag.title }}</a>, 
        {% endfor %}
    </p>

    <p>
        {{ post.content }}
    </p>
    <br>
    <a href="{% url 'blog:home' %}">Blog Index</a>

    <hr>
    <p>


        {% for cmnt in comments %}
            {{ cmnt.name }} _ {{ cmnt.email }} _ <code>{{cmnt.created}}</code>
            <p>
                {{ cmnt.content }}
            </p>
        {% endfor %}


    </p>

{% endif %}

blog/templates/blog/tag.html
{% if tag %}

    <p>
        <h2>{{ tag.title }}</h2>

        {% for post in tag.posts.all %}
        <p>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </p>
        {% endfor %}
    </p>
    <br>
    <a href="{% url 'blog:tags' %}">Tags Index</a>

{% endif %}

blog/templates/blog/tags.html
{% if tags %}
    {% for tag in tags %}

        <p>
            <a href="{{ tag.get_absolute_url }}">{{ tag.title }}
        </p>

    {% endfor %}
    <br>
    <a href="{% url 'blog:home' %}">Blog Index</a>

{% endif %}